package com.millervein.clinicalordertracker.clinicalorder;

public enum ClinicalOrderCloseReason {
	COMPLETED, COMBINED_PROCEDURE, INVALID_ORDER, OUT_OF_POCKET_COSTS, NERVOUS, NOT_INTERESTED, INSURANCE_ISSUES, MEDICAL_ISSUES, SCHEDULING_ISSUES, TRANSPORTATION_ISSUES, COMPRESSION_STOCKINGS;
}
